# Generated by Django 4.1.5 on 2023-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Translator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_translator',
        ),
    ]
