# Generated by Django 4.1.5 on 2023-02-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translator',
            new_name='Translatorr',
        ),
    ]
