# Generated by Django 3.2.5 on 2023-04-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
