# Generated by Django 3.2.5 on 2023-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_roommember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='roomID',
        ),
    ]
