# Generated by Django 3.2.5 on 2023-04-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230420_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='translator',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
